name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write  # Права на запись

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost

      - name: Configure with CMake
        run: |
          cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build the project
        run: |
          cmake --build .

      - name: Run tests
        run: |
          cmake --build . --target test

      - name: Create package
        run: |
          cmake --build . --target package

      - name: Create Release for Linux
        if: ${{ runner.os == 'Linux' }}
        id: create_release_linux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "linux-${{ github.run_number }}"
          release_name: "Release Linux ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}
          asset_path: ./main-0.0.${{ github.run_number }}-Linux.deb
          asset_name: main-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Create Release for macOS
        if: ${{ runner.os == 'macOS' }}
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "macos-${{ github.run_number }}"
          release_name: "Release macOS ${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset (macOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./main-0.0.${{ github.run_number }}-Darwin.dmg
          asset_name: main-0.0.${{ github.run_number }}-Darwin.dmg
          asset_content_type: application/x-apple-diskimage