name: 'C++ CI'

on:
  push:
    branches:
      - lab3
      - feature/github_actions
  release:
    types: [published]
jobs:
  build_on_Ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake libgtest-dev
      - name: Build Project
        run: |
            rm -rf build
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            cmake --build . --config Release
      - name: Run Tests
        run: |
            cd build
            ctest -V # Добавлен -V для verbose output
        # Проверьте опции и настройки в CMakeLists.txt
      
      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: release-zip
          path: ./your-project-name-Release.zip # Путь к Release ZIP-архиву
      - name: Build Debug
        run: |
          cmake . -DPATCH_VERSION=${{ github.run_number }} -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug
          cmake --build . --target package --config Debug
      - name: Upload Debug Asset
        uses: actions/upload-artifact@v3
        with:
          name: debug-deb
          path: ./your-project-name-Debug.deb # Путь к Debug DEB-архиву
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}-Linux2
          release_name: Release ${{ github.run_number }} for linux3
          draft: false
          prerelease: false 
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lab3-0.0.${{ github.run_number }}-Linux.deb
          asset_name: lab3-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
  # Устанавливаем gtest с помощью Homebrew
      - run: |
          brew update
          brew install googletest
          brew info googletest

  # Конфигурируем проект с помощью CMake, используя номер запуска для PATCH_VERSION 
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}  
  # Строим проект с помощью CMake
      - run: cmake --build .
  # Запускаем тесты
      - run: cmake --build . --target test
  # Создаем пакет
      - run: cmake --build . --target package
  # Создаем релиз для MacOS
      - name: Create Release
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}-mac # Используем номер запуска для тега
          release_name: Realise ${{ github.run_number }} for mac3
          draft: false # Не публикуем релиз в черновике
          prerelease: false # Не публикуем как предварительную версию
  # Загружаем релизный ассет для MacOS
      - name: Upload Release Asset (MacOS)
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./lab3-0.0.${{ github.run_number }}-Darwin.zip
          asset_name: lab3-0.0.${{ github.run_number }}-Darwin.zip
          asset_content_type: application/zip